# -*- coding: utf-8 -*-
"""pl_analysis

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1g4Y2XvmXxt7H3R3r0UJMovnOZgzYtFU9
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv('pl_data.csv')

df.head()

df.describe()

#getting the count of the non-null values
#also the data types of the coulumn entries
df.info()

#checking if there is some null value inside the data set
#df.isnull() could be used directly but it won't be clear
df.isnull().sum()

#to know about all the columns assigned to every row entry
df.columns.values

#position of the teams on the basis of overall performance
df[['Position','Team']]

#positioning of teams on the basis of Goal Difference(F-A)
#to avoid the permanent sorting of the whole dataframe we use it's copy to carry out the operation
s1 = df.copy()
GD = s1.sort_values(by='GD', ascending=False)
GD.head(20)

#positioning of teams on the basis of Games Played
s2 = df.copy()
GP = s2.sort_values(by='GP', ascending=False)
GP.head(20)

#positioning of teams on the basis of wins
s3 = df.copy()
W = s3.sort_values(by='W', ascending=False)
W.head(20)
#similary we can do it other columns too

#barplot on the basis of points gained by indivisual team
Team = df['Team'].head(20)
P = df['P'].head(20)
fig = plt.figure(figsize =(50,10))
plt.bar(Team[0:20], P[0:20])
#show the bar graph
plt.show()

#whishkers plot
df.boxplot()

#histogram
fig = plt.figure(figsize = (15,20))
ax = fig.gca()
df.hist(ax = ax)