# -*- coding: utf-8 -*-
"""SCRAPING PL Table

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tAXOZt6atam_pGUre6K4B4fIMCkMdYqD
"""

#importing the required libraries
from bs4 import BeautifulSoup 
import requests 
import pandas as pd

base_url = "https://www.skysports.com/premier-league-table"
#getting the contents of the web page
r = requests.get(base_url)

# Creating BeautifulSoup object
soup = BeautifulSoup(r.text,'html.parser')
#the below two comments are used to verify the tables and their classes
#for table in soup.find_all('table'):
#    print(table.get('class')
tables = soup.find_all('table')
table = soup.find('table', class_='standing-table__table callfn')

#creating a dataframe
df = pd.DataFrame(columns = ['Position','Team','GP','W','D','L','F','A','GD','P'])
# Collecting Ddata
for row in table.tbody.find_all('tr'):    
    data = row.find_all('td')
    Position = data[0].text.strip()
    Team = data[1].text.strip()
    GP = data[2].text.strip()
    W = data[3].text.strip()
    D = data[4].text.strip()
    L = data[5].text.strip()
    F = data[6].text.strip()
    A = data[7].text.strip()
    GD = data[8].text.strip()
    P = data[9].text.strip()
    df = df.append({'Position':Position,'Team':Team,'GP':GP,'W':W,'D':D,'L':L,'F':F,'A':A,'GD':GD,'P':P},ignore_index=True)

#checking the first few entries of the data set
df.head()

from google.colab import drive
drive.mount('drive')
#converting the dataframe to csv and saving it on google drive
df.to_csv('/content/drive/My Drive/pl_data.csv', encoding='utf-8', index=False)